name: envcontext
on:
 push:

env:
 var1: 'env variable is local variables and vars is global variables'

jobs:
 env-context:
  runs-on: ubuntu-latest
  steps:
   - name: Env
     run: echo "${{env.var1}}"
