name: First Workflows

on:
  issues:
  push:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: First Step
       run: echo "Hello GitHub Action with Ankit"
       
  second-job:
    runs-on: windows-latest
    steps:
     - name: Second Step
       run: echo "Hello GitHub Action with Ankit in Second Step"
  


       
    
