name: Second Workflows

on:
  issues:
  push:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Setup Java JDK
       uses: actions/setup-java@v4.7.0
       with:
          distribution: 'temurin'
          java-version: '21'
            
      
       
 
