name: Template
on:
 workflow_call:
  inputs:
    message:
     description: "Message to be printed"
     required: true
     type: string
     
jobs:
  print-message:
   runs-on: ubuntu-latest
   steps:
    - name: Print Message
      run: echo "${{inputs.message}}"
     
   
    
